spring.application.name=Kaffe
server.port=8081

spring.sql.init.data-locations=classpath:kaffeknd_spring.sql
spring.datasource.url=jdbc:mysql://localhost:3306/kaffeknd_spring?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=kaffe
spring.datasource.password=kaffe
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.servlet.session.persistent=false

app.jakarta.sync-url=http://localhost:8080/Kaffeknd_war_exploded/sync
app.geocoding.url=https://nominatim.openstreetmap.org/search?format=json&q=

server.error.include-stacktrace=never